# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import alertmanager_pb2 as alertmanager__pb2


class AlertManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Alert = channel.unary_unary(
                '/AlertManager/Alert',
                request_serializer=alertmanager__pb2.AlertRequest.SerializeToString,
                response_deserializer=alertmanager__pb2.Status.FromString,
                )
        self.handleReceiptConfirmation = channel.unary_unary(
                '/AlertManager/handleReceiptConfirmation',
                request_serializer=alertmanager__pb2.ReceiptConfirmation.SerializeToString,
                response_deserializer=alertmanager__pb2.Status.FromString,
                )


class AlertManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Alert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def handleReceiptConfirmation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlertManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Alert': grpc.unary_unary_rpc_method_handler(
                    servicer.Alert,
                    request_deserializer=alertmanager__pb2.AlertRequest.FromString,
                    response_serializer=alertmanager__pb2.Status.SerializeToString,
            ),
            'handleReceiptConfirmation': grpc.unary_unary_rpc_method_handler(
                    servicer.handleReceiptConfirmation,
                    request_deserializer=alertmanager__pb2.ReceiptConfirmation.FromString,
                    response_serializer=alertmanager__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AlertManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AlertManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Alert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AlertManager/Alert',
            alertmanager__pb2.AlertRequest.SerializeToString,
            alertmanager__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def handleReceiptConfirmation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AlertManager/handleReceiptConfirmation',
            alertmanager__pb2.ReceiptConfirmation.SerializeToString,
            alertmanager__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
