# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alertconfirmer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61lertconfirmer.proto\x1a\x1bgoogle/protobuf/empty.proto\",\n\x13ReceiptConfirmation\x12\x15\n\rnotifcationId\x18\x01 \x01(\x03\x32W\n\x0e\x41lertConfirmer\x12\x45\n\x13\x63onfirmAlertReceipt\x12\x14.ReceiptConfirmation\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alertconfirmer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECEIPTCONFIRMATION._serialized_start=53
  _RECEIPTCONFIRMATION._serialized_end=97
  _ALERTCONFIRMER._serialized_start=99
  _ALERTCONFIRMER._serialized_end=186
# @@protoc_insertion_point(module_scope)
