# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import alertsender_pb2 as alertsender__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class AlertSenderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendNotification = channel.unary_unary(
                '/AlertSender/sendNotification',
                request_serializer=alertsender__pb2.NotifcationRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class AlertSenderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlertSenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.sendNotification,
                    request_deserializer=alertsender__pb2.NotifcationRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AlertSender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AlertSender(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AlertSender/sendNotification',
            alertsender__pb2.NotifcationRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
