# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alertsender.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11\x61lertsender.proto"N\n\x13NotificationRequest\x12\x15\n\remail_address\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t".\n\rRequestStatus\x12\x0c\n\x04okay\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2I\n\x0b\x41lertSender\x12:\n\x10SendNotification\x12\x14.NotificationRequest\x1a\x0e.RequestStatus"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "alertsender_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _NOTIFICATIONREQUEST._serialized_start = 21
    _NOTIFICATIONREQUEST._serialized_end = 99
    _REQUESTSTATUS._serialized_start = 101
    _REQUESTSTATUS._serialized_end = 147
    _ALERTSENDER._serialized_start = 149
    _ALERTSENDER._serialized_end = 222
# @@protoc_insertion_point(module_scope)
