name: Docker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    env:
      SENDER_IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ALERTSENDER_APP_NAME }}:latest
      MANAGER_IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_MANAGER_APP_NAME }}:latest
      CONFIRMER_IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_CONFIRMER_APP_NAME }}:latest
      REMINDER_IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REMINDER_APP_NAME }}:latest
    steps:
      - name: Login
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build sender docker
        run: ./scripts/build-docker.sh alertsender $SENDER_IMAGE_NAME
        shell: bash

      - name: Build confirmer docker
        run: ./scripts/build-docker.sh alertconfirmer $CONFIRMER_IMAGE_NAME
        shell: bash

      - name: Build manager docker
        run: ./scripts/build-docker.sh alertmanager $MANAGER_IMAGE_NAME
        shell: bash

      - name: Build reminder docker
        run: ./scripts/build-docker.sh alertreminder $REMINDER_IMAGE_NAME
        shell: bash

      - name: Deploy sender docker
        run: ./scripts/deploy.sh ${{ secrets.GCP_ALERTSENDER_APP_NAME }} $SENDER_IMAGE_NAME
        shell: bash

      - name: Deploy confirmer docker
        run: ./scripts/deploy.sh ${{ secrets.GCP_CONFIRMER_APP_NAME }} $CONFIRMER_IMAGE_NAME
        shell: bash

      - name: Deploy manager docker
        run: ./scripts/deploy.sh ${{ secrets.GCP_MANAGER_APP_NAME }} $MANAGER_IMAGE_NAME
        shell: bash

      - name: Deploy reminder docker
        run: ./scripts/deploy.sh ${{ secrets.GCP_REMINDER_APP_NAME }} $REMINDER_IMAGE_NAME
        shell: bash
